### ISSUE TITLE
Missing version properties in package.json

### ISSUE THREAD

**Issue by PaulRosset** [segmentio/create-next-app#33]
Hello,

vs code emit a warning (problem) because there is no `version` properties in the `package.json` freshly created. There is a particular reason to not add it ? or just to keep the file as simple as possible ?

**Comment by stephenmathieson** [comment]
Hey Paul,

There's no version property because it isn't required for the generated app to "work". If this is giving you trouble, you can either add the property to the outputted package.json on your own, or send a PR which adds the property to [our default template](https://github.com/segmentio/create-next-app/blob/v0.5.3/lib/templates/default/package.json) =)

Closing for now.
